export { default as LandingTryCafe } from './LandingTryCafe';
export { default as LandingSafeFlexible } from './LandingSafeFlexible';
export { default as LandingPlugPlay } from './LandingPlugPlay';
export { default as LandingFunEasy } from './LandingFunEasy';
export { default as LandingHybridPolicy } from './LandingHybridPolicy';
export { default as LandingFooter } from './LandingFooter';
export { default as LandingHero } from './LandingHero';
export { default as LandingLeaders } from './LandingLeaders';
export { default as LandingMyTeamCafe } from './LandingMyTeamCafe';
